import { pick } from '../../core/language.ts';

const zh = {
  // index.ts
  navLabel: '运行诊断',
  navGroup: '系统',
  pageTitle: '运行诊断',
  pageDesc: '查看 bot 的运行状态、会话活动、事件与日志；运行参数和系统提示词在「设置」中管理。',
  subRun: '运行',
  subSessions: '会话统计',
  subEvents: '事件流',
  subRunlog: '运行日志',
  subTools: '工具表',
  netOffline: '接口不可达',
  toolsNote: (msg: string) => `完整工具表接口不可用：${msg}；上方是当前主循环那一份。`,

  // tools.ts
  ioGroup: (name: string | undefined) => `IO 工具 · ${name}`,
  groupCore: '原生动作 · core',
  groupPersona: '记忆 / 文件工具 · Persona',
  noDescription: '（未填写工具说明）',
  paramCount: (n: number) => `${n} 个参数`,
  schemaNote: '代码注册的只读 Schema。工具说明、参数类型、必填约束与嵌套结构在这里统一查看。',
  paramHeadPath: '参数路径',
  paramHeadType: '类型',
  paramHeadConstraint: '约束',
  paramHeadDesc: '说明',
  required: '必填',
  optional: '可选',
  noParams: '这个工具没有声明参数',
  copySchema: '复制 schema',
  fullSchema: '完整 JSON Schema',
  toolsTitle: '工具库',
  toolsDesc: '主循环当前发给模型的整张工具表:说明、参数约束与完整 JSON Schema。全部只读。',
  toolCount: (n: number) => `${n} 个`,
  toolsFilter: '筛选工具名或说明…',
  toolsEmpty: '工具表为空——主循环启动后会在这里出现',

  // events.ts
  eventsDesc: '事件库＝bot 的经历（外部世界发生的事，agent 可查）。core 内部事件不进这里。',
  allSources: '全部来源',
  showArchive: '显示原始归档',
  showArchiveTitle: '摄取刻落的 archive-only 原始事件，与发车刻的投影同源同文',
  loadEarlier: '← 加载更早',
  evHeadTime: '时间',
  evHeadSource: '来源',
  evHeadType: '类型',
  evHeadText: '正文',
  noEvents: '暂无事件',

  // run.ts
  runTitle: '运行态',
  runDesc: '只观察——模型、存储这些控制在「控制台」。',
  noStatus: '暂无状态',
  statContext: '上下文',
  statMessages: 'session 消息',
  statCache: '缓存命中',
  statRounds: '本批轮数',
  statBatches: '累计批次',
  statEvents: '事件库',
  statOnline: '终端在线',
  statRun: '运行',
  unitMsgs: '条',
  unitEvents: '条',
  unitPeople: '人',
  runPaused: '暂停',
  runBlocked: '闹钟阻断',
  runRunning: '进行',

  // runlog.ts
  currentRun: '当前 run',
  allLevels: '全部级别',
  areaPlaceholder: '区域前缀,如 worlds.minecraft', // arch-allow: 日志区域筛选框的示例前缀,只是示意文字
  grepPlaceholder: '正则,匹配内容与 data',
  roundPlaceholder: '轮次',
  roundField: '轮次',
  refresh: '刷新',
  runlogDesc: 'core 内部运行日志——只给人看，agent 不可见。',
  logHeadTime: '时间',
  logHeadLevel: '级别',
  logHeadArea: '区域',
  logHeadMsg: '内容',
  noLog: '暂无日志',

  // sessions.ts
  sessionsTitle: '会话统计',
  sessionsDesc: '主意识与各潜意识 fork 本次运行以来的 token 累计与缓存命中。跨重启的历史看「用量 · 成本」。',
  sesHeadStatus: '状态',
  sesHeadCalls: '调用',
  sesHeadInput: '输入 tok',
  sesHeadCache: '缓存命中',
  sesHeadOutput: '输出 tok',
  sesHeadMsgs: '消息',
  noSessions: '暂无 session',
  running: '进行中',
  ended: '已结束',
};

const en: typeof zh = {
  // index.ts
  navLabel: 'Diagnostics',
  navGroup: 'System',
  pageTitle: 'Diagnostics',
  pageDesc: 'Inspect the bot\'s run state, session activity, events and logs; run parameters and the system prompt are managed under "Settings".',
  subRun: 'Run',
  subSessions: 'Sessions',
  subEvents: 'Events',
  subRunlog: 'Run log',
  subTools: 'Tools',
  netOffline: 'API unreachable',
  toolsNote: (msg: string) => `Full tool table endpoint unavailable: ${msg}; shown above is the main loop's current copy.`,

  // tools.ts
  ioGroup: (name: string | undefined) => `IO tools · ${name}`,
  groupCore: 'Native actions · core',
  groupPersona: 'Memory / file tools · Persona',
  noDescription: '(no tool description)',
  paramCount: (n: number) => `${n} params`,
  schemaNote: 'Read-only schema registered in code. Tool description, parameter types, required constraints and nesting are all viewable here.',
  paramHeadPath: 'Path',
  paramHeadType: 'Type',
  paramHeadConstraint: 'Constraint',
  paramHeadDesc: 'Description',
  required: 'required',
  optional: 'optional',
  noParams: 'This tool declares no parameters',
  copySchema: 'Copy schema',
  fullSchema: 'Full JSON Schema',
  toolsTitle: 'Tool library',
  toolsDesc: 'The full tool table the main loop currently sends to the model: descriptions, parameter constraints and the full JSON Schema. Read-only.',
  toolCount: (n: number) => `${n} tools`,
  toolsFilter: 'Filter by tool name or description…',
  toolsEmpty: 'Tool table is empty — it appears here once the main loop starts',

  // events.ts
  eventsDesc: 'Event store = the bot\'s experience (things that happened in the outside world; the agent can query it). core-internal events do not go here.',
  allSources: 'All sources',
  showArchive: 'Show raw archive',
  showArchiveTitle: 'Archive-only raw events written at ingest; same source and text as the projection written at dispatch',
  loadEarlier: '← Load earlier',
  evHeadTime: 'Time',
  evHeadSource: 'Source',
  evHeadType: 'Type',
  evHeadText: 'Text',
  noEvents: 'No events yet',

  // run.ts
  runTitle: 'Loop status',
  runDesc: 'Observation only — model and storage controls live under "Console".',
  noStatus: 'No status yet',
  statContext: 'Context',
  statMessages: 'session messages',
  statCache: 'Cache hit',
  statRounds: 'Rounds this batch',
  statBatches: 'Total batches',
  statEvents: 'Event store',
  statOnline: 'Terminal online',
  statRun: 'Run',
  unitMsgs: 'msgs',
  unitEvents: 'events',
  unitPeople: 'users',
  runPaused: 'paused',
  runBlocked: 'schedule blocked',
  runRunning: 'running',

  // runlog.ts
  currentRun: 'Current run',
  allLevels: 'All levels',
  areaPlaceholder: 'Area prefix, e.g. worlds.minecraft', // arch-allow: 日志区域筛选框的示例前缀,只是示意文字
  grepPlaceholder: 'Regex, matches message and data',
  roundPlaceholder: 'Round',
  roundField: 'Round',
  refresh: 'Refresh',
  runlogDesc: 'core internal run log — for humans only; invisible to the agent.',
  logHeadTime: 'Time',
  logHeadLevel: 'Level',
  logHeadArea: 'Area',
  logHeadMsg: 'Message',
  noLog: 'No log entries',

  // sessions.ts
  sessionsTitle: 'Session stats',
  sessionsDesc: 'Token totals and cache hits for the main session and each subconscious fork since this run started. For history across restarts see "Usage · Cost".',
  sesHeadStatus: 'Status',
  sesHeadCalls: 'Calls',
  sesHeadInput: 'Input tok',
  sesHeadCache: 'Cache hit',
  sesHeadOutput: 'Output tok',
  sesHeadMsgs: 'Messages',
  noSessions: 'No sessions yet',
  running: 'running',
  ended: 'ended',
};

export const S = pick({ zh, en });
