import { pick } from '../../core/language.ts';
import type { EnvPromptOrigin } from '../../../../core/prefix.ts';

const zh = {
  // index.ts
  title: '系统提示词',
  introDesc: '整条 system 前缀在这里摊开成一份可编辑的文档。左边的标签标出每一块从哪开始，'
    + '灰底的块是运行时现拼的、改不了。改完按 **Ctrl+S** 写回文件，重载后替换当前 session 的前缀。'
    + '两侧栏拖边可以调宽窄。',
  reloadSession: '重载当前 session',
  reloading: '正在重载…',
  prefixReloaded: '前缀已重载',
  leaveUnsaved: '有改动还没保存（Ctrl+S），离开就丢了。确定离开？',
  saving: '保存中…',
  saved: '已保存',
  saveFailedFor: (title: string, msg: string) => `${title} 保存失败：${msg}`,
  savedList: (names: string) => `✓ 已保存 ${names}；重载后生效`,
  dirtyCount: (n: number) => `${n} 处改动还没保存（Ctrl+S）`,
  fillNowMultiline: '此刻填入（多行块）',
  fillNow: '此刻填入',
  varUnreported: '(没人报这个值——模板里用了它就会原样留在前缀里)',
  varEmpty: '(此刻为空，会落到缺省文案)',
  flagEditable: (key: string, origin: EnvPromptOrigin | undefined) =>
    `可编辑：${key}${origin === 'deployment' ? '（本部署的覆盖）' : origin === 'package' ? '（人格包的覆盖；保存后成为本部署的覆盖）' : origin === 'module' ? '（World 默认；保存后成为本部署的覆盖）' : ''}`,
  flagReadonly: '来自代码，只读',
  sourceMissing: (key: string) => `源「${key}」找不到`,
  fromCode: '来自代码',
  originDeployment: '本部署的覆盖',
  originPackage: '人格包的覆盖',
  originWorld: 'World 默认',
  listSep: '、',
  warnSep: '；',
  prefixEmpty: '前缀现在是空的',
  prefixUnavailable: '这个部署不提供前缀预览（/api/prompts/prefix 不可用）',
  prefixStats: (n: number, tok: string) => `${n} 块 · 渲染后约 ${tok} tokens`,
  loadFailed: (msg: string) => `加载失败：${msg}`,

  // view.ts
  warnUnknownVars: (list: string) => `模板里的 ${list} 没人填,会原样出现在前缀里`,
  warnUnusedVars: (list: string) => `${list} 声明了但没用到`,
  varPanelTitle: '这份模板的占位符',
  multiline: '多行',
  varUnreportedShort: '(没人报这个值)',
  varEmptyShort: '(此刻为空,会落到缺省文案)',
  leaveUnsavedNamed: (names: string) => `有未保存的模板改动（${names}）。离开并放弃？`,
  editableTemplate: '可编辑模板',
  cardDescDefault: '保存到源文件；重载系统前缀后对当前 session 生效。',
  loadedFromDeployment: '已从本部署的覆盖文件载入（不进版本控制，是你自己的那份）',
  loadedFromPackage: '人格包自带的覆盖；保存后成为本部署的覆盖，包里那份不动',
  loadedFromWorld: 'World 自带的默认模板；保存后成为本部署的覆盖， World 那份不动',
  loadedFromSource: '已从源文件载入',
  unsaved: '● 未保存',
  saveToFile: '保存到文件',
  resetToWorld: '恢复 World 默认',
  savedResult: (result: string) => `✓ ${result}；重载前缀后生效`,
  saveFailed: (msg: string) => `保存失败：${msg}`,
  saveFailedToast: '保存失败',
  resetTitle: (title: string) => `恢复「${title}」的 World 默认？`,
  resetBody: '会删掉本 bot 对它的覆盖文件，这份模板回到 World 自带的版本；未保存的改动一并丢弃。',
  resetting: '恢复中…',
  resetDone: '已恢复 World 默认',
  resetFailed: (msg: string) => `恢复失败：${msg}`,
  resetFailedToast: '恢复失败',
  noTemplatesScoped: '这个归属下没有可编辑的模板',
  noTemplates: '没有可编辑的提示词模板',
  templatesLoadFailed: (msg: string) => `模板加载失败：${msg}`,

  // editor.ts
  saveHintDirty: '按 Ctrl+S 保存',
};

const en: typeof zh = {
  // index.ts
  title: 'System prompt',
  introDesc: 'The whole system prefix is laid out here as one editable document. The flags on the left mark where each block starts; '
    + 'grey blocks are assembled at runtime and cannot be edited. Press **Ctrl+S** to write changes back to file; a reload replaces the current session\'s prefix. '
    + 'Drag the edges of the side columns to resize them.',
  reloadSession: 'Reload current session',
  reloading: 'Reloading…',
  prefixReloaded: 'Prefix reloaded',
  leaveUnsaved: 'There are unsaved changes (Ctrl+S); leaving discards them. Leave anyway?',
  saving: 'Saving…',
  saved: 'Saved',
  saveFailedFor: (title: string, msg: string) => `${title} failed to save: ${msg}`,
  savedList: (names: string) => `✓ Saved ${names}; takes effect after reload`,
  dirtyCount: (n: number) => `${n} unsaved changes (Ctrl+S)`,
  fillNowMultiline: 'Filled in now (multi-line block)',
  fillNow: 'Filled in now',
  varUnreported: '(nobody reports this value — if the template uses it, it stays in the prefix as is)',
  varEmpty: '(empty right now; falls back to the default text)',
  flagEditable: (key: string, origin: EnvPromptOrigin | undefined) =>
    `Editable: ${key}${origin === 'deployment' ? ' (this deployment\'s override)' : origin === 'package' ? ' (the package\'s override; saving makes it this deployment\'s override)' : origin === 'module' ? ' (World default; saving makes it this deployment\'s override)' : ''}`,
  flagReadonly: 'From code, read-only',
  sourceMissing: (key: string) => `Source "${key}" not found`,
  fromCode: 'From code',
  originDeployment: 'This deployment\'s override',
  originPackage: 'The package\'s override',
  originWorld: 'World default',
  listSep: ', ',
  warnSep: '; ',
  prefixEmpty: 'The prefix is empty right now',
  prefixUnavailable: 'This deployment provides no prefix preview (/api/prompts/prefix unavailable)',
  prefixStats: (n: number, tok: string) => `${n} blocks · about ${tok} tokens rendered`,
  loadFailed: (msg: string) => `Load failed: ${msg}`,

  // view.ts
  warnUnknownVars: (list: string) => `${list} in the template has nobody filling it; it will appear in the prefix as is`,
  warnUnusedVars: (list: string) => `${list} declared but unused`,
  varPanelTitle: 'Placeholders in this template',
  multiline: 'multi-line',
  varUnreportedShort: '(nobody reports this value)',
  varEmptyShort: '(empty right now; falls back to the default text)',
  leaveUnsavedNamed: (names: string) => `There are unsaved template changes (${names}). Leave and discard them?`,
  editableTemplate: 'editable template',
  cardDescDefault: 'Saved to the source file; takes effect for the current session after a system prefix reload.',
  loadedFromDeployment: 'Loaded from this deployment\'s override file (untracked — it is yours)',
  loadedFromPackage: 'The package\'s own override; saving makes it this deployment\'s override and leaves the package copy untouched',
  loadedFromWorld: 'The World\'s own default template; saving makes it this deployment\'s override and leaves the World\'s copy untouched',
  loadedFromSource: 'Loaded from the source file',
  unsaved: '● Unsaved',
  saveToFile: 'Save to file',
  resetToWorld: 'Restore World default',
  savedResult: (result: string) => `✓ ${result}; takes effect after a prefix reload`,
  saveFailed: (msg: string) => `Save failed: ${msg}`,
  saveFailedToast: 'Save failed',
  resetTitle: (title: string) => `Restore the World default for "${title}"?`,
  resetBody: 'Deletes this bot\'s override file for it; the template goes back to the World\'s own version. Unsaved changes are discarded too.',
  resetting: 'Restoring…',
  resetDone: 'World default restored',
  resetFailed: (msg: string) => `Restore failed: ${msg}`,
  resetFailedToast: 'Restore failed',
  noTemplatesScoped: 'No editable templates under this owner',
  noTemplates: 'No editable prompt templates',
  templatesLoadFailed: (msg: string) => `Failed to load templates: ${msg}`,

  // editor.ts
  saveHintDirty: 'Ctrl+S to save',
};

export const S = pick({ zh, en });
