import { pick } from '../core/language.ts';

const zh = {
  tagline: '事件驱动的人格 bot',
  groupPersonas: 'Persona',
  groupWorlds: 'World',
  moduleInstancesAria: 'World 实例',
  navAria: '控制台导航',
  settingsAria: '打开设置',
  settingsTitle: '设置',
  runResume: '继续运行',
  runPause: '暂停运行',
  runUnavailable: '运行控制不可用',
  shutdownAria: '关机',
  finishing: '正在按次序收尾…',
  shutdownTitle: '关机(按次序收尾并退出进程)',
  restartAria: '重启',
  restartTitleSupervised: '重启(按次序收尾,启动器重新拉起)',
  restartTitleUnsupervised: '重启(没有启动器循环:退出后要手动启动)',
  sequence: '按次序收尾并退出进程:按住事件投递 → World 停机(托管的外部进程与存档都在这一步)'
    + ' → Provider 实例停机 → 状态落盘 → 关闭控制台。',
  confirmShutdownTitle: '⚠ 关机',
  confirmRestartTitle: '⚠ 重启',
  restartSupervisedNote: '退出后启动器立即重新拉起,回来是暂停态,去控制台点「继续」上线。',
  restartUnsupervisedNote: '⚠ 这个进程不是启动器起的:退出后不会自动回来,需要手动重新启动。',
  halfMinute: '最长约半分钟,期间别关窗口。',
  confirmShutdownAgainTitle: '⚠⚠ 确认关机?',
  confirmShutdownAgainBody: '进程会退出,控制台随之关闭。要再上线得回到启动器重新启动。',
  confirmRestartAgainTitle: '⚠⚠ 确认重启?',
  confirmRestartAgainSupervised: '进程会退出并由启动器重新拉起;控制台断开几十秒后自己回来。',
  confirmRestartAgainUnsupervised: '进程会退出且不会自动回来。要再上线得回到启动器重新启动。',
  finishingToast: '正在按次序收尾…别关窗口。',
  stepIncomplete: '未完成',
  doneShutdown: '已关机',
  doneRestartSupervised: '已退出,等待启动器拉起',
  doneRestart: '已退出',
  resultLocalIncomplete: '本地收尾完成,有步骤没走完',
  resultExternalUnverified: '本地已关机,外部状态未确认',
  resultUnverified: '收尾完成,状态未确认',
  resultDefault: '已收尾。',
  noReceipt: (msg: string) =>
    `没拿到收尾回执(${msg});进程可能已经退出,逐步结果去 data/runlog.jsonl 的 shutdown 条目里看。`,
  docTitle: (name: string) => `控制台 · ${name}`,
};

const en: typeof zh = {
  tagline: 'An event-driven persona bot',
  groupPersonas: 'Personas',
  groupWorlds: 'Worlds',
  moduleInstancesAria: 'World instances',
  navAria: 'Console navigation',
  settingsAria: 'Open settings',
  settingsTitle: 'Settings',
  runResume: 'Resume',
  runPause: 'Pause',
  runUnavailable: 'Run control unavailable',
  shutdownAria: 'Shut down',
  finishing: 'Shutting down in order…',
  shutdownTitle: 'Shut down (finish in order, then exit the process)',
  restartAria: 'Restart',
  restartTitleSupervised: 'Restart (finish in order; the launcher relaunches)',
  restartTitleUnsupervised: 'Restart (no launcher loop: start manually after exit)',
  sequence: 'Finish in order and exit the process: hold event delivery → stop IO worlds (managed external processes and saves happen here)'
    + ' → stop provider instances → persist state → close the console.',
  confirmShutdownTitle: '⚠ Shut down',
  confirmRestartTitle: '⚠ Restart',
  restartSupervisedNote: 'The launcher relaunches right after exit; it comes back paused — press "Resume" in the console to go live.',
  restartUnsupervisedNote: '⚠ This process was not started by the launcher: it will not come back after exit; start it manually.',
  halfMinute: 'Takes up to about half a minute; do not close the window meanwhile.',
  confirmShutdownAgainTitle: '⚠⚠ Confirm shutdown?',
  confirmShutdownAgainBody: 'The process exits and the console closes with it. To go live again, start it from the launcher.',
  confirmRestartAgainTitle: '⚠⚠ Confirm restart?',
  confirmRestartAgainSupervised: 'The process exits and the launcher relaunches it; the console drops for a few dozen seconds, then comes back on its own.',
  confirmRestartAgainUnsupervised: 'The process exits and will not come back. To go live again, start it from the launcher.',
  finishingToast: 'Shutting down in order… do not close the window.',
  stepIncomplete: 'incomplete',
  doneShutdown: 'Shut down',
  doneRestartSupervised: 'Exited; waiting for the launcher',
  doneRestart: 'Exited',
  resultLocalIncomplete: 'Local shutdown finished with steps left incomplete',
  resultExternalUnverified: 'Shut down locally; external state unverified',
  resultUnverified: 'Shutdown finished; state unverified',
  resultDefault: 'Shutdown finished.',
  noReceipt: (msg: string) =>
    `No shutdown receipt (${msg}); the process may already have exited — see the shutdown entry in data/runlog.jsonl for step results.`,
  docTitle: (name: string) => `Console · ${name}`,
};

export const S = pick({ zh, en });
